blocks:
  -
    info: 'Licences : home'
    langcode: en
    uuid: 38810365-e710-46ec-bd28-0607a55766d7
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<h2>Licences</h2>\r\n\r\n<div class=\"content\">\r\n<p>We issue and maintain licences for gas, electricity and water companies to operate in Northern Ireland.</p>\r\n\r\n<p><a class=\"btn\" href=\"licences\">Find out more</a></p>\r\n</div>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Single Electricity Market : home'
    langcode: en
    uuid: 3323e044-bd58-4ee6-9c0a-44befed73bfe
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<h2>Single Electricity Market</h2>\r\n\r\n<div class=\"content\">\r\n<p>The Single Electricity Market (SEM) is the wholesale electricity market for the island of Ireland.</p>\r\n\r\n<p><a class=\"btn\" href=\"https://www.semcommittee.com/\" target=\"_blank\">Find out more</a></p>\r\n</div>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Water : home'
    langcode: en
    uuid: 19418964-9a33-4373-bf97-68707922fd9e
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>Documents about our regulation of water and sewerage services can all be accessed here</p>\r\n\r\n<div class=\"content\">\r\n<p><a class=\"btn\" href=\"publications/topic/water-9\">Water Publications</a></p>\r\n</div>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Gas : home'
    langcode: en
    uuid: 51aa0f08-d0bc-4780-a758-fad650f4d709
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>As the economic regulator of the gas industry we publish a range of documents about our work</p>\r\n\r\n<p><a class=\"btn\" href=\"publications/topic/gas-13/topic/gas-networks-7/topic/gas-retail-8\">Gas Publications</a></p>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Electricity : home'
    langcode: en
    uuid: 018e2ba1-0d09-4452-b2ee-b2eb97638d93
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p><span>We publish a wide range of documents relating to our regulation of the electricity sector</span></p>\r\n\r\n<p><a class=\"btn\" href=\"publications/topic/electricity-14/topic/electricity-networks-4/topic/electricity-retail-6/topic/electricity-wholesale-5\">Electricity Publications</a></p>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Consumer Information : Home'
    langcode: en
    uuid: a07ad254-b480-4b6f-a6a5-8bbfe86f83e4
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<h2>Consumer Information</h2>\r\n\r\n<p><a class=\"btn\" href=\"/consumer-information\">Find out more</a></p>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Footer subscription form'
    langcode: en
    uuid: 445ae893-ea77-4f0a-9da9-877d72660990
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>Subscribe to our news alert service.&nbsp;<br />\r\nGet the latest news updates directly to your email daily.</p>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Footer logo'
    langcode: en
    uuid: 832e1e63-d013-4245-8de7-78ebf653b236
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: '<img src="/sites/uregni/themes/uregni_theme/logo.svg" alt="Utility Regulator Home">'
          summary: ''
          format: full_html
  -
    info: 'Footer contact information'
    langcode: en
    uuid: 7efbaa9e-22a2-4819-9822-9d157ce79a78
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<address>Utility Regulator<br />\r\nQueens House<br />\r\n14 Queen Street<br />\r\nBelfast<br />\r\nBT1 6ED<br />\r\nTel: +44 (0) 28 9031 1575<br />\r\nFax: +44 (0) 28 9031 1740<br />\r\nEmail: <a href=\"mailto:info@uregni.gov.uk\">info@uregni.gov.uk</a></address>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Contact us contact info'
    langcode: en
    uuid: 8710f632-f7b7-4973-8fc9-74f71a191f76
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<h3>By post</h3>\r\n\r\n<address>Utility Regulator<br />\r\nQueens House<br />\r\n14 Queen Street<br />\r\nBelfast<br />\r\nBT1 6ED</address>\r\n\r\n<h3>By phone and fax</h3>\r\n\r\n<p>Tel: +44 (0) 28 9031 1575<br />\r\nFax: +44 (0) 28 9031 1740</p>\r\n\r\n<h3>By email</h3>\r\n\r\n<p><a href=\"mailto:info@uregni.gov.uk\">info@uregni.gov.uk</a><br />\r\nTo contact individual staff members:<br />\r\nfirstname.surname@uregni.gov.uk</p>\r\n\r\n<h3>Find us</h3>\r\n\r\n<p>Click here to <a href=\"/files/uregni/media-files/Map.pdf\">download a map <span> (PDF&nbsp;158 KB)</span></a>.</p>\r\n"
          summary: null
          format: basic_html
  -
    info: 'Investors in people'
    langcode: en
    uuid: 052be7c3-1273-444b-8bac-3b1e3f2ed47a
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p><img alt=\"Investors in People logo\" src=\"/sites/uregni/themes/uregni_theme/images/iip-logo.png\" /></p>\r\n"
          summary: ''
          format: full_html
  -
    info: 'Diversity Mark'
    langcode: en
    uuid: a2e573eb-b012-4880-9cc7-9ac974195e20
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<drupal-media data-align=\"center\" data-entity-type=\"media\" data-entity-uuid=\"5cdfa998-67ca-449e-87b2-c923f4263a1d\"></drupal-media>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Disability Confident'
    langcode: en
    uuid: 8d49e3ec-7a63-4639-948f-17c50b30b0ea
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p><img alt=\"Disability Confident logo\" src=\"/sites/uregni/themes/uregni_theme/images/disability-confident-logo.png\" /></p>\r\n"
          summary: ''
          format: full_html
  -
    info: 'Social links'
    langcode: en
    uuid: a8acec22-29a6-41f8-b6e1-c8c4eaf4f412
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
  -
    info: banner_deep
    langcode: en
    uuid: b58eae79-abeb-443c-9120-ec9987c74133
    bundle: banner_deep
    revision_id: null
    rev_id_current: null
    fields:
      field_banner_image:
        -
          target_id: '9753'
      field_banner_image_overlay: {  }
      field_teaser: {  }
  -
    info: 'Comparing energy deals and switching supplier'
    langcode: en
    uuid: 671ff2c8-0091-44d2-a1d2-5893eafef54e
    bundle: card_standard
    revision_id: null
    rev_id_current: null
    fields:
      field_image: {  }
      field_link:
        -
          uri: 'internal:/'
          title: test
          options: {  }
      field_teaser:
        -
          value: 'Teaser can go here'
      field_title_link: {  }
  -
    info: 'Getting help and support'
    langcode: en
    uuid: d80526f2-7c42-48d2-af9a-90a15ea368a2
    bundle: card_standard
    revision_id: null
    rev_id_current: null
    fields:
      field_image: {  }
      field_link: {  }
      field_teaser:
        -
          value: 'Teaser can go here'
      field_title_link: {  }
  -
    info: 'What we do to protect you'
    langcode: en
    uuid: a7c2aba0-7e5f-4b4a-8600-3845fb87561f
    bundle: card_standard
    revision_id: null
    rev_id_current: null
    fields:
      field_image: {  }
      field_link: {  }
      field_teaser:
        -
          value: 'Teaser can go here'
      field_title_link: {  }
  -
    info: banner_deep
    langcode: en
    uuid: 845f833a-2fd3-44b2-8217-3881f1d6811b
    bundle: banner_deep
    revision_id: null
    rev_id_current: null
    fields:
      field_banner_image:
        -
          target_id: '9871'
      field_banner_image_overlay: {  }
      field_teaser: {  }
  -
    info: 'Household consumers'
    langcode: en
    uuid: 603c107a-a2b0-42f5-aee9-fdb81c322968
    bundle: card_wide
    revision_id: null
    rev_id_current: null
    fields:
      field_image:
        -
          target_id: '9836'
      field_link: {  }
      field_teaser: {  }
      field_title_link:
        -
          uri: 'entity:node/5'
          title: ''
          options: {  }
  -
    info: 'Business consumers'
    langcode: en
    uuid: ee2f3391-9a64-49b2-8057-de4b6ee081ee
    bundle: card_wide
    revision_id: null
    rev_id_current: null
    fields:
      field_image:
        -
          target_id: '9854'
      field_link: {  }
      field_teaser: {  }
      field_title_link:
        -
          uri: 'internal:/'
          title: ''
          options: {  }
  -
    info: banner_deep
    langcode: en
    uuid: 428787dd-66ba-4b2c-9565-047df83e5dfb
    bundle: banner_deep
    revision_id: null
    rev_id_current: null
    fields:
      field_banner_image:
        -
          target_id: '9863'
      field_banner_image_overlay: {  }
      field_teaser: {  }
  -
    info: 'Comparing deals'
    langcode: en
    uuid: d1f24af5-6c84-479d-9050-2bd81a522a4b
    bundle: card_standard
    revision_id: null
    rev_id_current: null
    fields:
      field_image:
        -
          target_id: '9864'
      field_link: {  }
      field_teaser: {  }
      field_title_link: {  }
  -
    info: 'Advice and guidance'
    langcode: en
    uuid: a51ca022-5bf4-493a-96fc-5161821e2682
    bundle: card_standard
    revision_id: null
    rev_id_current: null
    fields:
      field_image:
        -
          target_id: '9865'
      field_link: {  }
      field_teaser: {  }
      field_title_link: {  }
  -
    info: 'Protecting consumers'
    langcode: en
    uuid: 90c1c15b-27e5-4b72-94e4-f1e1578ab25e
    bundle: card_standard
    revision_id: null
    rev_id_current: null
    fields:
      field_image:
        -
          target_id: '9866'
      field_link: {  }
      field_teaser: {  }
      field_title_link: {  }
