blocks:
  -
    info: Chair
    langcode: en
    uuid: 4f248e42-57d6-4abc-8f6c-7a09be259ca3
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<drupal-media data-align=\"center\" data-entity-type=\"media\" data-entity-uuid=\"6ab5545b-2a09-4253-8928-207dcb8a917b\"></drupal-media>\r\n\r\n<div class=\"image-caption\">\r\n<div class=\"home-name\">\r\n<p>Sir Robert Chote</p>\r\n</div>\r\n\r\n<div class=\"home-role\">\r\n<p>Chairman of the Northern Ireland Fiscal Council</p>\r\n</div>\r\n</div>\r\n"
          summary: ''
          format: full_html
  -
    info: 'Terms of reference'
    langcode: en
    uuid: f2e0a5bc-46e9-4eb0-9eb6-a282ac3b4fcf
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>The Council’s initial Terms of Reference reflect the commitments in the 2020 New Decade New Approach (NDNA) agreement. We are currently gathering feedback from stakeholders on our potential work programme and these initial ToR. We would welcome your suggestions, which you can email to <a href=\"mailto:info@nifiscalcouncil.org\">info@nifiscalcouncil.org</a>.</p>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Front Column 1'
    langcode: en
    uuid: b2997871-2795-409d-a89f-c77c4f2f3c78
    bundle: front_3_col
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>The Council’s initial Terms of Reference reflect the commitments in the 2020 New Decade New Approach (NDNA) agreement. &nbsp;We are currently gathering feedback from stakeholders on our potential work programme and these initial ToR. &nbsp;We would welcome your suggestions, which you can email to <a href=\"mailto:info@nifiscalcouncil.org\">info@nifiscalcouncil.org</a>.</p>\r\n"
          summary: ''
          format: basic_html
      field_image:
        -
          target_id: '3'
      field_link:
        -
          uri: 'entity:node/3'
          title: 'Terms of reference'
          options: {  }
  -
    info: 'Front Column 2'
    langcode: en
    uuid: 7ea2c017-3b21-48ec-95b1-7671506b3433
    bundle: front_3_col
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
      field_image:
        -
          target_id: '4'
      field_link:
        -
          uri: 'internal:/news'
          title: 'Latest news'
          options: {  }
  -
    info: 'Front Column 3'
    langcode: en
    uuid: 33104c25-ab1f-4f87-b622-9995dd8a9276
    bundle: front_3_col
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>The NI Fiscal Council is in the process of joining the OECD’s network of parliamentary budget officials and independent fiscal institutions. &nbsp;It is one of relatively few such institutions set up at a sub-national level. &nbsp;As a recently set up Fiscal Council, we are excited to join the network, and to learn from international experiences of other Independent Fiscal Institutions.</p>\r\n"
          summary: ''
          format: basic_html
      field_image:
        -
          target_id: '5'
      field_link:
        -
          uri: 'https://www.oecd.org/unitedkingdom/'
          title: OECD
          options: {  }
  -
    info: 'Contact us'
    langcode: en
    uuid: 67257ad0-f172-4348-8745-931a230e09e5
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>General email: <a href=\"mailto:info@nifiscalcouncil.org\">info@nifiscalcouncil.org</a></p>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Front bottom first'
    langcode: en
    uuid: 35594316-28de-4990-81bc-2f5297969db6
    bundle: front_3_col
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
      field_image:
        -
          target_id: '6'
      field_link:
        -
          uri: 'entity:node/17'
          title: 'Breakdown of planned spending by the NI Executive, 2021/22'
          options: {  }
  -
    info: 'Front bottom second'
    langcode: en
    uuid: de503132-c4d7-4e92-b3c7-8cdcf5d0cb56
    bundle: front_3_col
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
      field_image:
        -
          target_id: '7'
      field_link:
        -
          uri: 'entity:node/18'
          title: 'Sources of funding for NIE Budget, 2021/22'
          options: {  }
