audit_button_text: 'Audit this published content'
audit_button_hover_text: 'Click this link to indicate you have checked this content for accuracy and relevance'
audit_confirmation_text: 'Click this button to indicate that you have audited this published content and are happy that it is still accurate and relevant.'
audit_content_types:
  basic_page: basic_page
  consultation: 0
  contact: 0
  feature: 0
  featured_content_list: 0
  layout_page: 0
  link: 0
  news: 0
  profile: 0
  publication: 0
_core:
  default_config_hash: 3SEIckwYL56FAPOaQjHj9GcV2CUC9lkT-AxU07onAWE
