_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: 111659a8-d725-4e3b-a74b-94b061335de4
name: 'Fiscal Commission NI'
mail: admin@fiscalcommissionni.org
slogan: ''
page:
  403: ''
  404: ''
  front: /node/6
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to the Independent Fiscal Commission for Northern Ireland'
frontpage_show_title: 1
