_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: ad5bb45b-cc83-4a11-b048-5cca60024c3b
name: 'Northern Ireland Policing Board'
mail: lluis@websitedevelopment.ltd.uk
slogan: ''
page:
  403: /
  404: /
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to the Northern Ireland Policing Board'
frontpage_show_title: 0
