proxy:
  appserver:
    - uregni.gov.uk.lndo.site
    - liofa.eu.lndo.site
    - fictcommission.org.lndo.site
    - community-relations.org.uk.lndo.site
services:
  uregni_solr:
    type: solr:7
    portforward: true
    core: default
    config:
      dir: .lando/config/solr/7.x/default
