proxy:
  appserver:
    - uregni.gov.uk.lndo.site
    - liofa.eu.lndo.site
    - community-relations.org.uk.lndo.site
    - odscni.org.uk.lndo.site
    - attorneygeneralni.gov.uk.lndo.site
    - employmenttribunalsni.co.uk.lndo.site
    - fiscalcommissionni.org.lndo.site
    - nifiscalcouncil.org.lndo.site
    - niauditoffice.gov.uk.lndo.site
    - octf.gov.uk.lndo.site
    - urologyservicesinquiry.org.uk.lndo.site
    - mahinquiry.org.uk.lndo.site
    - independentreviewofeducation.org.uk.lndo.site
    - nipolicingboard.org.uk.lndo.site
    - pbni.org.uk.lndo.site
    - investnireview.org.uk.lndo.site
    - pcsps.org.lndo.site
    - cscsreviewni.net.lndo.site
    - mentalhealthchampion-ni.org.uk.lndo.site
services:
  uregni_solr:
    type: solr:7
    portforward: true
    core: default
    config:
      dir: .lando/config/solr/7.x/default
  niauditoffice_solr:
    type: solr:7
    portforward: true
    core: default
    config:
      dir: .lando/config/solr/7.x/default
  nipolicingboard_solr:
    type: solr:7
    portforward: true
    core: default
    config:
      dir: .lando/config/solr/7.x/default
  pbni_solr:
    type: solr:7
    portforward: true
    core: default
    config:
      dir: .lando/config/solr/7.x/default
  pcsps_solr:
    type: solr:7
    portforward: true
    core: default
    config:
      dir: .lando/config/solr/7.x/default
  attorneygeneralni_solr:
    type: solr:7
    portforward: true
    core: default
    config:
      dir: .lando/config/solr/7.x/default
  mentalhealthchampionni_solr:
    type: solr:7
    portforward: true
    core: default
    config:
      dir: .lando/config/solr/7.x/default
