#############################################################################
###                           --== IMPORTANT ==--                         ###
#############################################################################
# If you require changes to this file you must edit the file within the     #
# original repository.Any changes here will be overwritten when the project #
# is built.                                                                 #
#############################################################################
name: unity_1
proxy:
    appserver:
        - uregni.gov.uk.lndo.site
        - odscni.org.uk.lndo.site
        - fiscalcommissionni.org.lndo.site
        - mahinquiry.org.uk.lndo.site
        - nifiscalcouncil.org.lndo.site
        - octf.gov.uk.lndo.site
        - niauditoffice.gov.uk.lndo.site
        - employmenttribunalsni.co.uk.lndo.site
        - independentreviewofeducation.org.uk.lndo.site
        - nipolicingboard.org.uk.lndo.site
        - pbni.org.uk.lndo.site
        - investnireview.org.uk.lndo.site
        - attorneygeneralni.gov.uk.lndo.site
        - cscsreviewni.net.lndo.site
        - pcsps.org.lndo.site
        - urologyservicesinquiry.org.uk.lndo.site
services:
    uregni_solr:
        type: 'solr:7'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/7.x/default
    odscni_solr:
        type: 'solr:7'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/7.x/default
    fiscalcommissionni_solr:
        type: 'solr:7'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/7.x/default
    mahinquiry_solr:
        type: 'solr:7'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/7.x/default
    nifiscalcouncil_solr:
        type: 'solr:7'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/7.x/default
    octf_solr:
        type: 'solr:7'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/7.x/default
    niauditoffice_solr:
        type: 'solr:7'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/7.x/default
    employmenttribunalsni_solr:
        type: 'solr:7'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/7.x/default
    independentreviewofeducation_solr:
        type: 'solr:7'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/7.x/default
    nipolicingboard_solr:
        type: 'solr:7'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/7.x/default
    pbni_solr:
        type: 'solr:7'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/7.x/default
    investnireview_solr:
        type: 'solr:7'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/7.x/default
    attorneygeneralni_solr:
        type: 'solr:7'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/7.x/default
    cscsreviewni_solr:
        type: 'solr:7'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/7.x/default
    pcsps_solr:
        type: 'solr:7'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/7.x/default
    urologyservicesinquiry_solr:
        type: 'solr:7'
        portforward: true
        core: default
        config:
            dir: .lando/config/solr/7.x/default
