# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/user_guide/reference/platform-app-yaml.html

# The name of this app. Must be unique within a project.
name: 'unity'

# The runtime the application uses.
type: 'php:7.4'

dependencies:
  php:
    composer/composer: '^2'

runtime:
  # Enable the redis extension so Drupal can communicate with the Redis cache.
  extensions:
    - apcu
    - redis

# The relationships of the application with services or other applications.
#
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `:`.
relationships:
  #fictcommission_solr: 'solr:fictcommission'
  uregni_solr: 'solr:uregni'
  redis: 'redis:redis'
  fictcommission: 'db:fictcommission'
  uregni: 'db:uregni'
  liofa: 'db:liofa'
  odscni: 'db:odscni'
  attorneygeneralni: 'db:attorneygeneralni'
  employmenttribunalsni: 'db:employmenttribunalsni'
  hatecrimereviewni: 'db:hatecrimereviewni'
  fiscalcommissionni: 'db:fiscalcommissionni'
  nifiscalcouncil: 'db:nifiscalcouncil'

# The size of the persistent disk of the application (in MB).
disk: 20480

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
  '/web/files':
    source: local
    source_path: 'files'
  '/tmp':
    source: local
    source_path: 'tmp'
  '/private':
    source: local
    source_path: 'private'
  '/.drush':
    source: local
    source_path: 'drush'
  '/drush-backups':
    source: local
    source_path: 'drush-backups'
  '/.console':
    source: local
    source_path: 'console'

# Configuration of the build of this application.
build:
  flavor: composer

# The hooks executed at various points in the lifecycle of the application.
hooks:
  build: |
    set -e
  # The deploy hook runs after your application has been deployed and started.
  deploy: |
    set -e

    # For each multi site - rebuild caches, run db-updates and import config.
    for site in uregni odscni hatecrimereviewni fiscalcommissionni nifiscalcouncil attorneygeneralni employmenttribunalsni liofa fictcommission
    do
      echo "****** $site deployment ******"
      cd /app/web/sites/$site
      drush -l $site -y cache-rebuild
      drush -l $site -y updatedb
      drush -l $site -y config-import
      drush -l $site import-all-if-installed safe
    done

# The configuration of app when it is exposed to the web.
web:
  # Specific parameters for different URL prefixes.
  locations:
    '/':
      # The folder from which to serve static assets, for this location.
      #
      # This is a filesystem path, relative to the application root.
      root: 'web'

      # How long to allow static assets from this location to be cached.
      #
      # Can be a time in seconds, or -1 for no caching. Times can be
      # suffixed with "s" (seconds), "m" (minutes), "h" (hours), "d"
      # (days), "w" (weeks), "M" (months, as 30 days) or "y" (years, as
      # 365 days).
      expires: 5m

      # Whether to forward disallowed and missing resources from this
      # location to the application.
      #
      # Can be true, false or a URI path string.
      passthru: '/index.php'

      # Deny access to static files in this location.
      allow: false

      # Rules for specific URI patterns.
      rules:
        # Allow access to common static files.
        '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
          allow: true
        '^/robots\.txt$':
          allow: true
        '^/sitemap\.xml$':
          allow: true

        # Deny direct access to configuration files.
        '^/sites/sites\.php$':
          scripts: false
        '^/sites/[^/]+/settings.*?\.php$':
          scripts: false

    '/files':
      # Allow access to all files in the public files directory.
      allow: true
      expires: 1d
      passthru: '/index.php'
      root: 'web/files'

      # Do not execute PHP scripts.
      scripts: false

      rules:
        # Provide a longer TTL (2 weeks) for aggregated CSS and JS files.
        '^/sites/default/files/(css|js)':
          expires: 2w

# The configuration of scheduled execution.
crons:
  uregni:
    spec: '*/5 * * * *'
    cmd: 'cd web/sites/uregni ; drush core-cron'
  odscni:
    spec: '*/5 * * * *'
    cmd: 'cd web/sites/odscni ; drush core-cron'
  attorneygeneralni:
    spec: '*/5 * * * *'
    cmd: 'cd web/sites/attorneygeneralni ; drush core-cron'
  employmenttribunalsni:
    spec: '*/5 * * * *'
    cmd: 'cd web/sites/employmenttribunalsni ; drush core-cron'
  hatecrimereviewni:
    spec: '*/5 * * * *'
    cmd: 'cd web/sites/hatecrimereviewni ; drush core-cron'
