features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
  path: ''
favicon:
  use_default: 1
ga_tracking_disabled: 0
ga_tracking_disabled_eu: 1
twitter_profile_url: 'https://twitter.com/fiscal_ni'
facebook_profile_url: ''
linkedin_profile_url: ''
pinterest_profile_url: ''
youtube_profile_url: ''
instagram_profile_url: ''
