blocks:
  -
    info: 'What do PCSPs do?'
    langcode: en
    uuid: 98c1e54a-7028-4066-bf5e-d9c0f0857a19
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p><a class=\"btn\" data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"b9be6ef2-7b97-4696-b582-27d1c301df88\" href=\"/node/10\">View here</a></p>\r\n"
          summary: null
          format: basic_html
  -
    info: Contents
    langcode: en
    uuid: e57da459-cc29-4aa9-a36e-99b0b13d604c
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<ul>\r\n\t<li><a href=\"/node/10\">A quick look at their work</a></li>\r\n\t<li><a href=\"/node/14\">Events and meetings</a></li>\r\n\t<li><a href=\"/node/15\">Neighbourhood Watch</a></li>\r\n\t<li><a href=\"/publications\">Publications</a></li>\r\n\t<li><a href=\"/node/17\">Corporate Branding</a></li>\r\n</ul>\r\n"
          summary: null
          format: basic_html
  -
    info: Twitter
    langcode: en
    uuid: 7f940ed3-d21b-40b6-9aed-ba19b2ee25e1
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
  -
    info: 'Locate your PCSP'
    langcode: en
    uuid: 539554a0-6aac-490f-bc7d-d67893cff16b
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p><a class=\"btn\" data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"f1556372-7994-4b6e-af47-b579b952562a\" href=\"/node/13\">Read more</a></p>\r\n"
          summary: null
          format: basic_html
  -
    info: 'Find your PCSP on facebook'
    langcode: en
    uuid: f3e6af61-5a3d-4c42-9164-424b2bed5117
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>Find the following PCSPs on Facebook</p>\r\n\r\n<ul>\r\n\t<li><a href=\"https://www.facebook.com/ardsandnorthdownpcsp/\">Ards and North Down PCSP</a></li>\r\n\t<li><a href=\"https://www.facebook.com/antrimandnewtownabbeypcsp/\">Antrim &amp; Newtownabbey PCSP</a></li>\r\n\t<li><a href=\"https://www.facebook.com/belfastpcsp/\">Belfast PCSP</a></li>\r\n\t<li><a href=\"https://www.facebook.com/armaghbanbridgecraigavonpcsp/\">Armagh City, Banbridge &amp; Craigavon PCSP</a></li>\r\n\t<li><a href=\"https://www.facebook.com/derryandstrabanepcsp/?hc_ref=ARRz4WVJQM7x-Lw-f5Mv-ZpPluECqjh2k-7cM27SCOLcjk13hXwnjB9nTrCrPjD1m-0&amp;fref=nf\">Derry City &amp; Strabane PCSP</a></li>\r\n\t<li><a href=\"http://www.facebook.com/causewaycoastglenspcsp/\">Causeway Coast &amp; Glens PCSP</a></li>\r\n\t<li><a href=\"https://www.facebook.com/lisburnandcastlereaghpcsp/\">Lisburn &amp; Castlereagh PCSP</a></li>\r\n\t<li><a href=\"https://www.facebook.com/Fermanagh-Omagh-PCSP-831587116927844/\">Fermanagh &amp; Omagh PCSP</a></li>\r\n\t<li><a href=\"https://www.facebook.com/midulsterpcsp/\">Mid Ulster PCSP</a></li>\r\n\t<li><a href=\"http://www.facebook.com/midandeastantrimpcsp/\">Mid &amp; East Antrim PCSP</a></li>\r\n\t<li><a href=\"https://www.facebook.com/newrymourneanddownpcsp/\">Newry, Mourne &amp; Down PCSP</a></li>\r\n</ul>\r\n"
          summary: null
          format: basic_html
  -
    info: 'Contact information'
    langcode: en
    uuid: 30851f68-f5b9-4ccf-b5ae-1f0880c196c2
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<address>Northern Ireland Policing Board<br />\r\nWaterside Tower<br />\r\n31 Clarendon Road<br />\r\nClarendon Dock<br />\r\nBelfast<br />\r\nBT1 3BG<br />\r\n<br />\r\nTelephone: 028 9040 8500<br />\r\nFax: 028 9040 8540<br />\r\nEmail: <a href=\"mailto:information@nipolicingboard.org.uk\">information@nipolicingboard.org.uk</a></address>\r\n\r\n<address><br />\r\nDepartment of Justice<br />\r\nCommunity Safety Unit<br />\r\nRA4.02<br />\r\nCastle Buildings<br />\r\nStormont Estate<br />\r\nBelfast<br />\r\nBT4 3SQ</address>\r\n\r\n<address>Telephone: 028 9076 3000<br />\r\nEmail: <a href=\"mailto:DOJCSU_PDB.Mailbox@justice-ni.gov.uk\">DOJCSU_PDB.Mailbox@justice-ni.gov.uk</a></address>\r\n"
          summary: null
          format: basic_html
  -
    info: 'Social links'
    langcode: en
    uuid: f570d85e-bfdc-4655-997d-c94fb62d0406
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
  -
    info: 'Related links'
    langcode: en
    uuid: d8fbeabb-c564-4426-bdc3-0ff778759362
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<ul>\r\n\t<li><a href=\"https://www.nipolicingboard.org.uk/\">Northern Ireland Policing Board</a></li>\r\n\t<li><a href=\"https://www.psni.police.uk/\">Police Service of Northern Ireland</a></li>\r\n</ul>\r\n"
          summary: null
          format: basic_html
  -
    info: 'PCSPS Map'
    langcode: en
    uuid: 0f7211b2-8024-45fa-9729-134d87581e31
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
