taxonomies:
  publications_topics:
    -
      vid: publications_topics
      tid: '1'
      langcode: en
      name: 'Caseload Statistics'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: dc54394e-302f-4416-a8a6-35baa39401ae
    -
      vid: publications_topics
      tid: '2'
      langcode: en
      name: Legislation
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 600281c9-6db5-4ab7-b2c5-b467497e4d67
    -
      vid: publications_topics
      tid: '3'
      langcode: en
      name: Leaflets
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 838757d0-acad-46a0-94dd-df446a9e64f5
    -
      vid: publications_topics
      tid: '4'
      langcode: en
      name: 'Register of Interests'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: d8c821ce-2d6e-4d03-a6fb-dfe6980261fa
    -
      vid: publications_topics
      tid: '5'
      langcode: en
      name: Policies
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 32876ab6-3f46-4e84-9652-05962fee4798
    -
      vid: publications_topics
      tid: '6'
      langcode: en
      name: 'Stakeholder Survey Reports'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 79086ef6-de66-4563-8dff-587997df4bfa
    -
      vid: publications_topics
      tid: '7'
      langcode: en
      name: 'Other Statistical Reports'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 62a88739-c72a-4030-a3b6-c90d91b9ee81
    -
      vid: publications_topics
      tid: '8'
      langcode: en
      name: 'Key Facts and Figures'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 7d5f51eb-baa7-4794-a237-848ce89e459f
    -
      vid: publications_topics
      tid: '9'
      langcode: en
      name: 'Official Statistics'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 1a85bd6e-87d9-4b11-93ac-0732106b0b39
    -
      vid: publications_topics
      tid: '10'
      langcode: en
      name: 'Probation News Magazine'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 6d89b697-3112-420c-ba2a-ccc803eb2806
  site_topics: {  }
  tags: {  }
blocks:
  -
    info: 'Footer logos'
    langcode: en
    uuid: b17ee179-4796-45c3-af89-e89a1b99663e
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<ul>\r\n\t<li><img alt=\"W3C logo\" src=\"/sites/pbni/themes/pbni_theme/images/-logo.png\" /></li>\r\n\t<li><img alt=\"Freedom of Information logo\" src=\"/sites/pbni/themes/pbni_theme/images/foi-logo.png\" /></li>\r\n\t<li><img alt=\"Step to Excellence logo\" src=\"/sites/pbni/themes/pbni_theme/images/excellence-logo.png\" /></li>\r\n\t<li><img alt=\"Domestic violence logo\" src=\"/sites/pbni/themes/pbni_theme/images/dom-violence-logo.png\" /></li>\r\n</ul>\r\n"
          summary: null
          format: full_html
  -
    info: 'Social links'
    langcode: en
    uuid: f85057d4-a198-4ecc-9c48-5a9611f7e647
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
  -
    info: 'Footer Contact information'
    langcode: en
    uuid: 1284beeb-e3e7-41d2-a8f4-2bcfd6943974
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>Telephone 028 9052 2522</p>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Home page 3 links'
    langcode: en
    uuid: b3c731f7-5eef-4673-b249-d5b3f0a236ce
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<ul>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"3f7a6acc-349e-43a0-acf9-fcefaf9380aa\" href=\"/node/13\">Key facts and figures</a></li>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"d7150210-c301-43be-a718-801960561eb7\" href=\"/node/14\">Real life stories</a></li>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"f8e199f7-f591-439e-8313-962b31a1e0fc\" href=\"/node/15\">Programmes</a></li>\r\n</ul>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Home page 5 links'
    langcode: en
    uuid: 85227472-67d0-4a39-927c-0a70be16f609
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<ul>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"353a88c3-8706-49be-ab56-92260f091253\" href=\"/node/8\">For people under supervision</a></li>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"13ad7648-bae7-4234-9fbe-29c1d8a74d5d\" href=\"/node/9\">For sentencers</a></li>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"f86a2396-8e82-4901-8e2d-285dfb4dd5a2\" href=\"/node/10\">For victims</a></li>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"f5123684-430c-4c5d-8553-895cd27f71fb\" href=\"/node/11\">For the community</a></li>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"f7425c58-6884-4c82-82ae-4528f8be2570\" href=\"/node/12\">For Partner organisations</a></li>\r\n</ul>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Twitter block'
    langcode: en
    uuid: 141fe351-5b7c-49cf-8c51-889b817c7d7c
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
