taxonomies:
  publications_topics:
    -
      vid: publications_topics
      tid: '1'
      langcode: en
      name: 'Caseload Statistics'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: dc54394e-302f-4416-a8a6-35baa39401ae
    -
      vid: publications_topics
      tid: '2'
      langcode: en
      name: Legislation
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 600281c9-6db5-4ab7-b2c5-b467497e4d67
    -
      vid: publications_topics
      tid: '3'
      langcode: en
      name: Leaflets
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 838757d0-acad-46a0-94dd-df446a9e64f5
    -
      vid: publications_topics
      tid: '4'
      langcode: en
      name: 'Register of Interests'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: d8c821ce-2d6e-4d03-a6fb-dfe6980261fa
    -
      vid: publications_topics
      tid: '5'
      langcode: en
      name: Policies
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 32876ab6-3f46-4e84-9652-05962fee4798
    -
      vid: publications_topics
      tid: '6'
      langcode: en
      name: 'Stakeholder Survey Reports'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 79086ef6-de66-4563-8dff-587997df4bfa
    -
      vid: publications_topics
      tid: '7'
      langcode: en
      name: 'Other Statistical Reports'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 62a88739-c72a-4030-a3b6-c90d91b9ee81
    -
      vid: publications_topics
      tid: '8'
      langcode: en
      name: 'Key Facts and Figures'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 7d5f51eb-baa7-4794-a237-848ce89e459f
    -
      vid: publications_topics
      tid: '9'
      langcode: en
      name: 'Official Statistics'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 1a85bd6e-87d9-4b11-93ac-0732106b0b39
    -
      vid: publications_topics
      tid: '10'
      langcode: en
      name: 'Probation News Magazine'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 6d89b697-3112-420c-ba2a-ccc803eb2806
  site_topics: {  }
  tags: {  }
blocks:
  -
    info: 'Twitter block'
    langcode: en
    uuid: 141fe351-5b7c-49cf-8c51-889b817c7d7c
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
  -
    info: 'Home page 5 links'
    langcode: en
    uuid: 85227472-67d0-4a39-927c-0a70be16f609
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<h2>We Deliver Services</h2>\r\n\r\n<ul>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"56e739e6-61a2-4396-a62e-a38cf679d29c\" href=\"/node/126\">In the Community</a></li>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"f86a2396-8e82-4901-8e2d-285dfb4dd5a2\" href=\"/node/10\">With Victims</a></li>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"7c375b9b-a27e-4ca4-9858-e552cd6397ed\" href=\"/node/127\">In Courts</a></li>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"b99e0cc0-1289-404f-95c6-4660fbebedbf\" href=\"/node/128\">In Prisons</a></li>\r\n</ul>\r\n"
          summary: null
          format: basic_html
  -
    info: 'Home page 3 links'
    langcode: en
    uuid: b3c731f7-5eef-4673-b249-d5b3f0a236ce
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<ul>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"ab4abd7d-028f-477e-8138-b75e2d03fcb7\" href=\"/node/160\">Key facts and figures</a></li>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"42859512-8dac-4700-852a-855341914396\" href=\"/node/23\">Careers</a></li>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"438943e7-6a44-4653-98c7-76ee77c6e86f\" href=\"/node/266\">Real life stories</a></li>\r\n</ul>\r\n"
          summary: null
          format: basic_html
  -
    info: 'Footer Contact information'
    langcode: en
    uuid: 1284beeb-e3e7-41d2-a8f4-2bcfd6943974
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>Telephone 028 9052 2522</p>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Social links'
    langcode: en
    uuid: f85057d4-a198-4ecc-9c48-5a9611f7e647
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
  -
    info: 'Footer logos'
    langcode: en
    uuid: b17ee179-4796-45c3-af89-e89a1b99663e
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<ul>\r\n\t<li><a href=\"https://www.w3.org/WAI/WCAG1AA-Conformance\"><img alt=\"W3C logo\" src=\"/sites/pbni/themes/pbni_theme/images/w3c-logo.png\" /></a></li>\r\n\t<li><a href=\"/access-information\"><img alt=\"Freedom of Information logo\" src=\"/sites/pbni/themes/pbni_theme/images/foi-logo.png\" /></a></li>\r\n\t<li><a href=\"http://www.cforc.org/\"><img alt=\"Step to Excellence logo\" src=\"/sites/pbni/themes/pbni_theme/images/excellence-logo.png\" /></a></li>\r\n\t<li><a href=\"https://www.onustraining.co.uk/gold-award\"><img alt=\"Domestic violence logo\" src=\"/sites/pbni/themes/pbni_theme/images/dom-violence-logo.png\" /></a></li>\r\n</ul>\r\n"
          summary: null
          format: full_html
