blocks:
  -
    info: 'What we do'
    langcode: en
    uuid: 8710f557-2dab-40d0-a4af-a0a19ba08a9b
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<h3>Financial Audit</h3>\r\n\r\n<ul>\r\n\t<li><a href=\"/node/30\">Central Government Audits</a></li>\r\n\t<li><a data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"78ed7a8b-2e96-4c00-ab32-d25f0c5f8719\" href=\"/node/31\">Local Government Audits</a></li>\r\n</ul>\r\n\r\n<h3>Value for money audit</h3>\r\n\r\n<p><a href=\"/node/32\"><span>Read more</span></a></p>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Footer Contact information'
    langcode: en
    uuid: 7853c171-cf18-4d0d-9133-3c2f7cc34147
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<address>Northern Ireland Audit Office<br />\r\n<span><span>106 University Street<br />\r\nBelfast<br />\r\nBT7 1EU</span></span><br />\r\nT: (028) 9025 1000<br />\r\nF: (028) 9025 1106 or (028) 9025 1051<br />\r\nE:&nbsp;<a href=\"mailto:info@niauditoffice.gov.uk\">info@niauditoffice.gov.uk</a></address>\r\n"
          summary: null
          format: basic_html
  -
    info: 'Footer Useful links'
    langcode: en
    uuid: 735e1f34-f69d-44f2-97da-b4a43be6df5f
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<ul>\r\n\t<li><a href=\"http://www.nao.org.uk/\">National Audit Office</a></li>\r\n\t<li><a href=\"http://www.audit-scotland.gov.uk/\">Audit Scotland</a></li>\r\n\t<li><a href=\"http://www.wao.gov.uk/\">Audit Wales</a></li>\r\n\t<li><a href=\"http://audgen.gov.ie/\">Office of the C&amp;AG Dublin</a></li>\r\n</ul>\r\n"
          summary: null
          format: basic_html
  -
    info: 'Footer subscription'
    langcode: en
    uuid: 8dc9a7f3-2fdb-4848-bf4a-ca89e2fc142c
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<h2>Subscribe to our news email alert service</h2>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Social links'
    langcode: en
    uuid: 6fc864c3-256a-4811-9bba-1cd4e3ec22be
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
