blocks:
  -
    info: 'Homepage image block'
    langcode: en
    uuid: 1a01f892-e9b6-4364-b752-e3caf6fa92de
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p><img alt=\"Judge Desmond Marrinan - Head of the review\" src=\"/sites/hatecrimereviewni/themes/hcr_theme/images/judge-marrinan.jpg\" /></p><p class='image-caption'>Judge Desmond Marrion Head of the Review </p>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Footer Contact information'
    langcode: en
    uuid: 6245254b-4901-4d7a-8705-6e312a2d46e5
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>Telephone: 028 9026 1395<br />\r\nEmail: <a href=\"mailto:enquiries@hatecrimereviewni.org.uk\">enquiries@hatecrimereviewni.org.uk</a><br />\r\n&nbsp;</p>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Footer Address information'
    langcode: en
    uuid: 3d8f1e48-b6fb-4bca-a637-280852bc16ce
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<address>Room 1.8, Block 1<br />\r\nKnockview Buildings<br />\r\nStormont Estate<br />\r\nBelfast<br />\r\nBT4 3SG</address>\r\n"
          summary: ''
          format: basic_html
menus: {  }
