<?php

use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;

/**
 * @file
 * Contains unity_migrations.module.
 */

function uregni_migrations_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  // Ignore entity queue as not used in D8 site.
  if ($migration->id() == 'upgrade_d7_field') {
    if ($row->getSource()['type'] == 'entityreference') {
      if (preg_match('/entityqueue_subqueue/', $row->getSource()['data'])) {
        return FALSE;
      }
    }
  }
}
