taxonomies:
  publications_topics: {  }
  site_topics: {  }
  tags: {  }
blocks:
  -
    info: 'About the inquiry'
    langcode: en
    uuid: 1e99ba1c-48c4-4b30-a65a-9564ab4dfacb
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur facilisis orci magna, vitae hendrerit libero dapibus vitae. Cras accumsan et neque eu molestie.</p>\r\n\r\n<p>Sed luctus semper elit molestie vehicula. &nbsp;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem ipsum dolor sit amet.</p>\r\n\r\n<p><a class=\"btn\" data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"f2a4cc8b-b718-473c-b7b0-5b71a5f6a877\" href=\"/node/8\">Read our Terms of Reference</a></p>\r\n"
          summary: ''
          format: basic_html
menus:
  -
    menu_name: main
    title: Home
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-50'
    langcode: en
    uuid: cfb1a15a-2061-4d1c-a552-1b0f82f7398b
  -
    menu_name: main
    title: 'Inquiry Team'
    parent: null
    uri: 'entity:node/3'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-49'
    langcode: en
    uuid: c7df6c78-e49e-4c76-9765-784d198dcca0
  -
    menu_name: main
    title: 'Contact us'
    parent: null
    uri: 'entity:node/4'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-46'
    langcode: en
    uuid: fd2ecd77-b97d-497e-af45-2c25f987c2d1
  -
    menu_name: main
    title: Support
    parent: null
    uri: 'entity:node/5'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-45'
    langcode: en
    uuid: 54535f03-a680-4a90-848c-dcc87e0a332b
  -
    menu_name: main
    title: 'Key Documents'
    parent: null
    uri: 'internal:/publications'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-48'
    langcode: en
    uuid: f845d049-3b5e-4742-9208-87f9dbccbe15
  -
    menu_name: menu-footer-links
    title: '© Crown Copyright'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-50'
    langcode: en
    uuid: a886aa5e-f5ee-4e49-864f-17ea37efd713
  -
    menu_name: menu-footer-links
    title: Cookies
    parent: null
    uri: 'entity:node/6'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-49'
    langcode: en
    uuid: 84b0a769-df01-49e8-8f74-e6e342ec7833
  -
    menu_name: menu-footer-links
    title: 'Accessibility statement'
    parent: null
    uri: 'entity:node/7'
    link_title: ''
    description: null
    enabled: '1'
    expanded: '0'
    weight: '-48'
    langcode: en
    uuid: 400f292a-ee97-4844-bb51-1e0cdaad823f
  -
    menu_name: main
    title: 'Sub page'
    parent: 'menu_link_content:c7df6c78-e49e-4c76-9765-784d198dcca0'
    uri: 'entity:node/11'
    link_title: null
    description: null
    enabled: '1'
    expanded: '0'
    weight: '0'
    langcode: en
    uuid: 9f79e8c7-f65c-4a37-bf1c-4a03ce50d936
