blocks:
  -
    info: 'About the Inquiry'
    langcode: en
    uuid: 1e99ba1c-48c4-4b30-a65a-9564ab4dfacb
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p><span><span><span><span>The establishment of the independent public Urology Services Inquiry was announced in a statement by the Health Minister, on 24 November 2020.</span></span></span></span></p>\r\n\r\n<p><a class=\"btn\" data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"84095f92-14a0-417a-acf4-5433f8bec2da\" href=\"/node/12\">Read our Terms of Reference</a></p>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Social links'
    langcode: en
    uuid: 254cc1c0-6f62-4535-9078-e8958427bfd4
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
  -
    info: 'Watch Hearings'
    langcode: en
    uuid: c0a2c18d-f026-4062-9ec0-807da2b3f017
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>When a Hearing is in session you can watch it by following the link below. Planned sitting dates and times are outlined on the timetable and are subject to change.</p>\r\n"
          summary: ''
          format: basic_html
menus:
  -
    menu_name: main
    title: Home
    parent: null
    uri: 'internal:/'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: en
    uuid: cfb1a15a-2061-4d1c-a552-1b0f82f7398b
  -
    menu_name: main
    title: 'Inquiry Team'
    parent: null
    uri: 'entity:node/3'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: en
    uuid: c7df6c78-e49e-4c76-9765-784d198dcca0
  -
    menu_name: main
    title: 'Contact us'
    parent: null
    uri: 'entity:node/4'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -46
    langcode: en
    uuid: fd2ecd77-b97d-497e-af45-2c25f987c2d1
  -
    menu_name: main
    title: Support
    parent: null
    uri: 'entity:node/5'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: -45
    langcode: en
    uuid: 54535f03-a680-4a90-848c-dcc87e0a332b
  -
    menu_name: main
    title: 'Key Documents'
    parent: null
    uri: 'internal:/publications'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: en
    uuid: f845d049-3b5e-4742-9208-87f9dbccbe15
  -
    menu_name: menu-footer-links
    title: '© Crown Copyright'
    parent: null
    uri: 'route:<nolink>'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -50
    langcode: en
    uuid: a886aa5e-f5ee-4e49-864f-17ea37efd713
  -
    menu_name: menu-footer-links
    title: Cookies
    parent: null
    uri: 'entity:node/6'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -49
    langcode: en
    uuid: 84b0a769-df01-49e8-8f74-e6e342ec7833
  -
    menu_name: menu-footer-links
    title: 'Accessibility statement'
    parent: null
    uri: 'entity:node/7'
    link_title: ''
    description: null
    enabled: true
    expanded: false
    weight: -48
    langcode: en
    uuid: 400f292a-ee97-4844-bb51-1e0cdaad823f
  -
    menu_name: main
    title: 'Sub page'
    parent: 'menu_link_content:c7df6c78-e49e-4c76-9765-784d198dcca0'
    uri: 'entity:node/11'
    link_title: null
    description: null
    enabled: true
    expanded: false
    weight: 0
    langcode: en
    uuid: 9f79e8c7-f65c-4a37-bf1c-4a03ce50d936
taxonomies:
  publications_topics:
    -
      vid: publications_topics
      tid: '1'
      langcode: en
      name: 'Terms of Reference'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 0fd21ff5-a6b7-445d-8193-e8bc825f15a7
    -
      vid: publications_topics
      tid: '2'
      langcode: en
      name: Protocols
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 60d3a2b1-3fb9-4fa9-875e-bc36ee04c4f6
    -
      vid: publications_topics
      tid: '3'
      langcode: en
      name: 'Restriction Orders'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 3d488d73-fb07-4c62-9cdb-851b2eb733b7
    -
      vid: publications_topics
      tid: '4'
      langcode: en
      name: Procedures
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 9abf6c62-c404-4f06-a5df-a837a0259049
    -
      vid: publications_topics
      tid: '5'
      langcode: en
      name: 'Data Protection'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 45f32336-67ea-448a-9578-c9dd0f1412ba
    -
      vid: publications_topics
      tid: '6'
      langcode: en
      name: 'Transcripts and Evidence called'
      description__value: null
      description__format: null
      weight: '0'
      parent: '0'
      uuid: 0fbb4148-d8c6-4cf4-b689-d043d3709462
  tags: {  }
