<?php

/**
 * @file
 * Contains uregni_breadcrumbs.module.
 */

use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * Implements hook_system_breadcrumb_alter().
 *
 * Altering the search view page breadcrumbs, when facets are selected the breadcrumb trail is overwritten.
 */
function uregni_breadcrumbs_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  $links = $breadcrumb->getLinks();
  $route_name = $route_match->getRouteName();

  // The publications view page has an extra breadcrumb linked to the about us page so we need to add this in to keep the existing structure.
  if ($route_name == 'view.publications_search.publication_search_page') {
    $about_us_link[] = Link::fromTextandUrl(t('About us'), Url::fromUri('internal:/about-us'));
    array_splice($links, 1, 0, $about_us_link);
  }
}
