_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: 4bd8e87f-40cc-4a1d-8722-d122094e3f68
name: 'Urology Services Inquiry'
mail: admin@usi.org.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node/9
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to Urology Services Inquiry'
frontpage_show_title: 0
