blocks:
  -
    info: 'Homepage Attorney General profile'
    langcode: en
    uuid: be7d98a4-718a-4831-b9fb-158b904898ee
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<drupal-media alt=\"Brenda King\" data-align=\"center\" data-entity-type=\"media\" data-entity-uuid=\"d8c4ffb6-250f-4e9e-a7b5-397e12b38942\"></drupal-media>\r\n"
          summary: ''
          format: basic_html
