name: 'Attorney General for Northern Ireland'
mail: admin@attorneygeneralni.gov.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
uuid: 368e9ece-3fd1-4a1f-810f-30871f29c4d5
frontpage_title: 'Welcome to Drupal site'
