_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: 9ee61300-5049-4c8e-acfd-76c3da9a4999
name: 'Attorney General for Northern Ireland'
mail: contact@attorneygeneralni.gov.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node/12
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: Welcome
frontpage_show_title: 1
