module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  config_filter: 0
  config_split: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  facets: 0
  facets_pretty_paths: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geolocation: 0
  geolocation_address: 0
  geolocation_google_maps: 0
  geolocation_google_static_maps: 0
  geolocation_search_api: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  linkit: 0
  media: 0
  media_library: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_tools: 0
  migrate_upgrade: 0
  moderation_sidebar: 0
  node: 0
  noreferrer: 0
  options: 0
  origins_ckeditor_enhancements: 0
  origins_common: 0
  origins_workflow: 0
  page_cache: 0
  path: 0
  path_alias: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  search: 0
  search_api: 0
  search_api_location: 0
  search_api_location_views: 0
  search_api_solr: 0
  simplei: 0
  structure_sync: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  twig_tweak: 0
  unity_common: 0
  unity_image_styles: 0
  unity_media: 0
  unity_search_pages: 0
  user: 0
  whatlinkshere: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  origins: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  nicsdru_unity_theme: 0
  uregni_theme: 0
profile: origins
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
