module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  config_filter: 0
  config_split: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  easy_install: 0
  editor: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_tools: 0
  migrate_upgrade: 0
  node: 0
  options: 0
  origins_common: 0
  page_cache: 0
  path: 0
  path_alias: 0
  rdf: 0
  redirect: 0
  search: 0
  search_api: 0
  search_api_solr: 0
  simplei: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  origins: 1000
theme:
  stark: 0
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
profile: origins
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
