blocks:
  -
    info: 'Licences : home'
    langcode: en
    uuid: 38810365-e710-46ec-bd28-0607a55766d7
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        value: "<h2>Licences</h2>\r\n\r\n<div class=\"content\">\r\n<p>We issue and maintain licences for gas, electricity and water companies to operate in Northern Ireland.</p>\r\n\r\n<p><a class=\"btn\" href=\"licences\">Find out more</a></p>\r\n</div>\r\n"
        summary: ''
        format: basic_html
  -
    info: 'Single Electricity Market : home'
    langcode: en
    uuid: 3323e044-bd58-4ee6-9c0a-44befed73bfe
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        value: "<h2>Single Electricity Market</h2>\r\n\r\n<div class=\"content\">\r\n<p>The Single Electricity Market (SEM) is the wholesale electricity market for the island of Ireland.</p>\r\n\r\n<p><a class=\"btn\" href=\"https://www.semcommittee.com/\" target=\"_blank\">Find out more</a></p>\r\n</div>\r\n"
        summary: ''
        format: basic_html
  -
    info: 'Water : home'
    langcode: en
    uuid: 19418964-9a33-4373-bf97-68707922fd9e
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        value: "<p>Documents about our regulation of water and sewerage services can all be accessed here</p>\r\n\r\n<div class=\"content\">\r\n<p><a class=\"btn\" href=\"publications/topic/Water\">Water Publications</a></p>\r\n</div>\r\n"
        summary: ''
        format: basic_html
  -
    info: 'Gas : home'
    langcode: en
    uuid: 51aa0f08-d0bc-4780-a758-fad650f4d709
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        value: "<p>As the economic regulator of the gas industry we publish a range of documents about our work</p>\r\n\r\n<p><a class=\"btn\" href=\"publications/topic/Gas/topic/Gas Retail/topic/Gas networks\">Gas Publications</a></p>\r\n"
        summary: ''
        format: basic_html
  -
    info: 'Electricity : home'
    langcode: en
    uuid: 018e2ba1-0d09-4452-b2ee-b2eb97638d93
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        value: "<p><span>We publish a wide range of documents relating to our regulation of the electricity sector</span></p>\r\n\r\n<p><a class=\"btn\" href=\"publications/topic/Electricity/topic/Electricity networks/topic/Electricity retail/topic/Electricity wholesale\">Electricity Publications</a></p>\r\n"
        summary: ''
        format: basic_html
  -
    info: 'Consumer Information : Home'
    langcode: en
    uuid: a07ad254-b480-4b6f-a6a5-8bbfe86f83e4
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        value: "<h2>Consumer Information</h2>\r\n\r\n<p><a class=\"btn\" href=\"/consumer-information\">Find out more</a></p>\r\n"
        summary: ''
        format: basic_html
