blocks:
  -
    info: 'Consumer Information : Home'
    langcode: en
    uuid: a07ad254-b480-4b6f-a6a5-8bbfe86f83e4
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        value: "<h2>Consumer Information</h2>\r\n\r\n<p><a class=\"btn\" href=\"/consumer-information\">Find out more</a></p>\r\n"
        summary: ''
        format: basic_html
