blocks:
  -
    info: 'Contact us contact info'
    langcode: en
    uuid: 8710f632-f7b7-4973-8fc9-74f71a191f76
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        value: "<h3>By post</h3>\r\n\r\n<address>Utility Regulator<br />\r\nQueens House<br />\r\n14 Queen Street<br />\r\nBelfast<br />\r\nBT1 6ED</address>\r\n\r\n<h3>By phone and fax</h3>\r\n\r\n<p>Tel: +44 (0) 28 9031 1575<br />\r\nFax: +44 (0) 28 9031 1740</p>\r\n\r\n<h3>By email</h3>\r\n\r\n<p><a href=\"mailto:info@uregni.gov.uk\">info@uregni.gov.uk</a><br />\r\nTo contact individual staff members:<br />\r\nfirstname.surname@uregni.gov.uk</p>\r\n\r\n<h3>Find us</h3>\r\n\r\n<p>Click here to <a href=\"https://www.uregni.gov.uk/sites/uregni/files/media-files/Map.pdf\">download a map <span> (PDF&nbsp;158 KB)</span></a>.</p>\r\n"
        summary: ''
        format: basic_html
