blocks:
  -
    info: Test
    langcode: en
    uuid: e5ad9d3d-9c0f-4f5b-8719-51f8ca846730
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        value: "<p>Test</p>\r\n"
        summary: ''
        format: basic_html
