blocks:
  -
    info: 'Footer logo'
    langcode: en
    uuid: 832e1e63-d013-4245-8de7-78ebf653b236
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        value: "<drupal-media data-align=\"center\" data-entity-type=\"media\" data-entity-uuid=\"3f27dc16-c684-45af-bc98-b8d23cc3d862\"></drupal-media>\r\n"
        summary: ''
        format: basic_html
