blocks:
  -
    info: 'Social links'
    langcode: en
    uuid: 36ce48a3-ce1c-462a-a244-4d36c9f469c7
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
