_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: c3db4695-813b-48b7-a28d-881c1e1e35a6
name: 'Office of the Discretionary Support Commissioner'
mail: eddwebdev@finance-ni.gov.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'The Office of the Discretionary Support Commissioner'
frontpage_show_title: 1
