project_type: unity
project_name: 'Unity 1'
project_id: 6tlkpwbr6tndk
sites:
    uregni:
        name: 'Utility Regulator'
        url: uregni.gov.uk
        solr: uregni
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/uregni ; drush core-cron'
        database: uregni
        status: production
        default: false
    odscni:
        name: 'Office of the Discretionary Support Commissioner'
        url: odscni.org.uk
        solr: odscni
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/odscni ; drush core-cron'
        database: odscni
        status: production
        default: false
    fiscalcommissionni:
        name: 'Fiscal Commission NI'
        url: fiscalcommissionni.org
        solr: fiscalcommissionni
        cron_spec: '10 * * * *'
        cron_cmd: 'cd web/sites/fiscalcommissionni ; drush core-cron'
        database: fiscalcommissionni
        status: production
        default: false
