<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function niauditoffice_common_preprocess_select(&$variables) {

  if ($variables['element']['#field_name'] === 'field_publication_topic') {
    $x = 1;
    $variables['attributes']['data-drupal-selector'] = 'edit-field-publication-type';
    $variables['attributes']['aria-describedby'] = 'edit-field-publication-type--description';
    $variables['attributes']['id'] = 'edit-field-publication-type';
    $variables['attributes']['name'] = 'field_publication_type';
  }
}

/**
 * Implements hook_theme().
 */
function niauditoffice_common_preprocess_form_element_label(&$variables) {
   if ($variables['element']['#id'] === 'edit-field-publication-topic') {
     $variables['attributes']['for'] = 'edit-field-publication-type';
   }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function niauditoffice_common_theme_suggestions_form_element_alter(array &$suggestions, array $variables, $hook) {
  $element = $variables['element'];
  $suggestions[] = $hook . '__' . $element['#field_name'];
}
