name: Liofa
mail: admin@liofa.eu
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
uuid: 8f57e357-3301-4fc7-a9e7-53ffe1c6b6b7
frontpage_title: 'Welcome to Drupal site'
