features:
  node_user_picture: 1
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
ga_tracking_disabled: 1
ga_tracking_disabled_eu: 0
twitter_profile_url: 'https://twitter.com/nipolicingboard'
facebook_profile_url: 'https://www.facebook.com/policingboard'
linkedin_profile_url: 'https://uk.linkedin.com/company/northernirelandpolicingboard'
pinterest_profile_url: ''
youtube_profile_url: 'https://www.youtube.com/user/nipolicingboard'
instagram_profile_url: ''
