<?php

/**
 * @file
 * Contains unity_common.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Form alter hook for the LinkIt dialogue box
 * presented in the WYSIWYG editor.
 */
function unity_common_form_linkit_editor_dialog_form_alter(array &$form, FormStateInterface $form_state) {

  // Hide option to open link in new window.
  $form['linkit_attributes']['target']['#access'] = FALSE;

  // Provide additional guidance information.
  $form['attributes']['href']['#description'] .= '<p>'
    . t('To reference an external URL type the full address, eg: https://www.nidirect.gov.uk') . '</p>'
    . '<p>' . t('To reference an e-mail address type the full address and select the "E-mail" option from the dropdown list.')
    . '</p>';
}

function unity_common_preprocess_node_add_list(&$variables) {
  $sorted_list = [];
  foreach ($variables['types'] as $type) {
    $thislink = $type['add_link'];
    $label = $thislink->getGeneratedLink();
    $bare_label = strip_tags($label);
    $sorted_list[$bare_label] = $type;
  }
  ksort($sorted_list);
  $variables['types'] = [];
  foreach($sorted_list as $item) {
    $variables['types'][$item['type']] = $item;
  }
}
