<?php

/**
 * @file
 * Custom code for search pages.
 */

/**
 * Implements hook_preprocess_views_view() for views_view.
 * Adding a singular/pluralised result count in the header of the search pages.
 *
 * @RenderElement("html_tag");
 */
function unity_search_pages_preprocess_views_view(array &$variables) {
  // Add view display ids to add result count to header of the search view.
  $display_ids = ['publication_search_page',
    'news_search_page',
    'consultations_search_page'
  ];

  foreach ($display_ids as $display_id) {
    if ($variables['display_id'] == $display_id) {
      // Ensure the search has items in an array.
      if (!empty($variables['view']->total_rows)) {

        // Count the number of items in the array.
        $number_of_items = $variables['view']->total_rows;

        // Choose which result text expression to use
        switch ($display_id) {
          case 'publication_search_page':
            $result = 'publication';
            break;
          case 'news_search_page':
            $result = 'news';
            break;
          case 'consultations_search_page':
            $result = 'consultation';
            break;
        }
        // Singular expression if only 1, if more pluralise.
        if ($number_of_items > 1 and $result != 'news') {
          $header_text = $result.'s';
        } else {
          $header_text = $result;
        }

        // Output the result.
        $variables['header']['result'] = [
          '#type' => 'html_tag',
          '#tag' => 'h2',
          '#attributes' => ['class' => 'current-search-item-results-count'],
          '#value' => t('@item_count @header_text',
            [
              '@item_count' => $number_of_items,
              '@header_text' => $header_text,
            ]),
        ];
      }
      else {
        $variables['header']['result'] = [
          '#type' => 'html_tag',
          '#tag' => 'h2',
          '#attributes' => ['class' => 'current-search-item-results-count'],
          '#value' => t('0 results'),
        ];
      }
    }
  }
}
