site_url_list: "https://www.independentreviewofeducation.org.uk/\r\nhttps://independentreviewofeducation.org.uk/\r\nhttp://www.independentreviewofeducation.org.uk/\r\nhttp://independentreviewofeducation.org.uk/"
