name: 'Commission on Flags, Identity, Culture and Tradition'
mail: admin@fictcommission.org
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
uuid: d149e516-aae6-485a-835a-9131fbe7d188
frontpage_title: 'Welcome to Drupal site'
frontpage_show_title: 0
