name: 'Employment Tribunals NI'
mail: admin@employmenttribunalsni.co.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
uuid: 0f498ad3-5442-4479-8dad-a905f368c944
frontpage_title: 'Welcome to Drupal site'
