_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: bf828570-725b-4a41-975a-0049dca0d714
name: 'Industrial Tribunals and the Fair Employment Tribunal Northern Ireland'
mail: eddwebdev@finance-ni.gov.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to the Industrial Tribunals and Fair Employment Tribunal'
frontpage_show_title: 1
