site_url_list: "https://employmenttribunalsni.co.uk\r\nhttps://www.employmenttribunalsni.co.uk\r\nhttp://employmenttribunalsni.co.uk\r\nhttp://www.employmenttribunalsni.co.uk"
site_url_list_exclude: "https://employmenttribunalsni.co.uk/OITFET_IWS/DecisionSearch.aspx\r\nhttps://employmenttribunalsni.co.uk/OITFET_IWS/Login.aspx"
