# Each route describes how an incoming URL is going to be processed by Platform.sh.
"https://www.fictcommission.org/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false
    headers: ['Accept', 'Accept-Language', 'X-Language-Locale']
    default_ttl: 3600
    # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"http://fictcommission.org/":
  type: redirect
  to: "http://www.fictcommission.org/"

"https://www.uregni.gov.uk/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false
    headers: ['Accept', 'Accept-Language', 'X-Language-Locale']
    default_ttl: 3600
    # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"http://uregni.gov.uk/":
  type: redirect
  to: "http://www.uregni.gov.uk/"

"https://www.liofa.eu/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false
    headers: ['Accept', 'Accept-Language', 'X-Language-Locale']
    default_ttl: 3600
    # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"http://liofa.eu/":
  type: redirect
  to: "http://www.liofa.eu/"

"https://www.odscni.org.uk/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false
    headers: ['Accept', 'Accept-Language', 'X-Language-Locale']
    default_ttl: 3600
    # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"http://odscni.org.uk/":
  type: redirect
  to: "http://www.odscni.org.uk/"

"https://www.attorneygeneralni.gov.uk/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false
    headers: ['Accept', 'Accept-Language', 'X-Language-Locale']
    default_ttl: 3600
    # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"http://attorneygeneralni.gov.uk/":
  type: redirect
  to: "http://www.attorneygeneralni.gov.uk/"

"https://www.employmenttribunalsni.co.uk/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false
    headers: ['Accept', 'Accept-Language', 'X-Language-Locale']
    default_ttl: 3600
    # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"http://employmenttribunalsni.co.uk/":
  type: redirect
  to: "http://www.employmenttribunalsni.co.uk/"

"https://www.hatecrimereviewni.org.uk/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false
    headers: ['Accept', 'Accept-Language', 'X-Language-Locale']
    default_ttl: 3600
    # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"http://hatecrimereviewni.org.uk/":
  type: redirect
  to: "http://www.hatecrimereviewni.org.uk/"

"https://www.fiscalcommissionni.org/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false
    headers: ['Accept', 'Accept-Language', 'X-Language-Locale']
    default_ttl: 3600
    # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"http://fiscalcommissionni.org/":
  type: redirect
  to: "http://www.fiscalcommissionni.org/"

"https://www.nifiscalcouncil.org/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false
    headers: ['Accept', 'Accept-Language', 'X-Language-Locale']
    default_ttl: 3600
    # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
    cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

"http://nifiscalcouncil.org/":
  type: redirect
  to: "http://www.nifiscalcouncil.org/"

"https://www.{all}/":
  type: upstream
  upstream: "unity:http"
  cache:
    enabled: false
    headers: ['Accept', 'Accept-Language', 'X-Language-Locale']
    default_ttl: 3600
    # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
    cookies: ['*']
"https://{all}/":
  type: redirect
  to: "https://www.{all}/"
