<?php

/**
 * @file
 * Contains unity_internal_link_checker.module.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\views\Entity\View;

/**
 * Implements hook_entity_presave().
 */
function unity_internal_link_checker_entity_presave(EntityInterface $entity) {
  if ($entity instanceof ContentEntityInterface) {
    if ($entity->hasField('body')) {
      $y = $entity->get('body')->value;
    }
  }
}
