_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
name: 'Mental Health Champion Northern Ireland'
mail: test@test.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
uuid: af095fd6-a277-4ad3-8c9d-3fee3143a071
frontpage_title: 'Welcome to Drupal site'
