blocks:
  -
    info: Featured
    langcode: en
    uuid: c88b7d01-d032-4942-a662-6f93a1239fb1
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body:
        -
          value: "<p>Content to follow</p>\r\n\r\n<p><a class=\"btn\" data-entity-substitution=\"canonical\" data-entity-type=\"node\" data-entity-uuid=\"12159410-63a4-4869-a63d-4e1086fad498\" href=\"/node/9\">Read more</a></p>\r\n"
          summary: ''
          format: basic_html
  -
    info: 'Social links'
    langcode: en
    uuid: d86601cf-011e-4cfa-858a-faba35fd5e33
    bundle: basic_block
    revision_id: null
    rev_id_current: null
    fields:
      body: {  }
