_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
langcode: en
uuid: 2203f22f-0b97-47da-ba52-893565b91155
name: 'Organised Crime Task Force'
mail: eddwebdev@finance-ni.gov.uk
slogan: ''
page:
  403: ''
  404: ''
  front: /node/8
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
frontpage_title: 'Welcome to Organised Crime Task Force'
frontpage_show_title: 0
