#!/usr/bin/env bash

## Description: RRe-builds the Unity themes for each site.
## Usage: rebuild-unity-site-themes
## Aliases: ddrbst
## Example: "ddev rebuild-unity-site-themes"
## HostWorkingDir: true

/var/www/html/build-themes.sh
