name: 'Northern Ireland Audit Office'
mail: test@test.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
langcode: en
default_langcode: en
_core:
  default_config_hash: IqFDJOUXgoqYSm39bzsb0BVMDSkw3b4-KD4YSUgMw7U
uuid: 6bc5a293-e4bb-4f46-98c6-7b3774d96a7b
frontpage_title: 'Welcome to Drupal site'
